### PR TITLE
Swagger documentation added

### PR DESCRIPTION
**Pull request by AxelDavid45**
The documentation is ready for the signup endpoint

### CODE REVIEW

**Review by angelozdev — APPROVED** [review]
Looks excellent!
are you using ESLint or Prettier?

**Comment by AxelDavid45** [comment]
> 
> 
> Looks excellent!
> are you using ESLint or Prettier?

Yes, NestJS comes with ESLint and Prettier, did you see anything bad formatted?

**Comment by angelozdev** [comment]
There is code written like this: {myvariable} and another like { myvariable }

**Comment by AxelDavid45** [comment]
> like

Ok let me see it

**Comment by AxelDavid45** [comment]
@angelozdev The changes are ready, can you confirm everything is OK?

**Pull request merged**
